### ISSUE TITLE
Publish to the Open VSX Registry

### ISSUE THREAD

**Issue by devgioele** [garlandcrow/vscode-helix#1]
Could we publish this extension to the [Open VSX Registry](https://open-vsx.org/)?

As explained in the [VSCodium documentation](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace), Microsoft's proprietary extension store cannot be available from open source distributions of Visual Studio Code, making this extension unreachable for many users.

Instructions are found in the [OpenVSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension).

**Comment by garlandcrow** [comment]
Thanks for the info! didnt know about that! will set that up with next release.
